In [2]:
import numpy as np   #import 

In [5]:
# array creation and printing 
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [9]:
a=[1,2,3,4,"hello"]
a

[1, 2, 3, 4, 'hello']

In [11]:
np.array(a)


array(['1', '2', '3', '4', 'hello'], dtype='<U21')

In [13]:
#vectors -- created in 1 dimesional(1 row) space
l=[1,2,3,4]
l

[1, 2, 3, 4]

In [14]:
#matrix -- 2 dimesional (rows are col)
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [15]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
#Array generation Functions 

In [20]:
#range  array range(arange)
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
#generate zeros in vector
arr = np.zeros(6)
arr #provides ans in vector 

array([0., 0., 0., 0., 0., 0.])

In [26]:
#generate zeros in matrix
arr = np.zeros((6,6))  #((m=no of rows , n=no of columns))
arr #provides ans in matrix

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [30]:
arr=np.ones(7)
arr
#OR
arr=np.ones((7,7))
arr

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [35]:
#linespace --> returns the evenly spread numbers in specific interval 
arr=np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [36]:
#Random generation functions


In [38]:
#generate randomg values in the range of 0 to 1 called normalization
np.random.rand(5)

array([0.07821977, 0.74940746, 0.88451385, 0.85617627, 0.46616265])

In [40]:
#generate randomg values in the range of 3 to -3 called standardisation
np.random.randn(5)

array([ 0.98089455, -0.66294703, -0.34242881,  1.93320786,  0.27006828])

In [42]:
#generates ramdom number in the rnage of 0 to 6 
np.random.randint(6)

2

In [44]:
#ganerated range of random number 
np.random.randint(10,20,10)  #(start=10,end=20,total number=10)


array([10, 16, 16, 16, 14, 11, 18, 18, 14, 10], dtype=int32)

In [45]:
#Array Attributes 

In [47]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
#gives shape of our matrix
arr.shape  #(row,col)

(3, 3)

In [50]:
#gives shape of our matrix
arr.size #how many elemts in the array

9

In [52]:
#gives data type of the array elements 
arr.dtype

dtype('int64')

In [53]:
#Array methods 


In [54]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
#minimum element in an array
arr.min()

np.int64(1)

In [56]:
#max element in an array
arr.max()

np.int64(9)

In [57]:
#gives sum of all elements in an array
arr.sum()

np.int64(45)

In [60]:
#only col wise sum
np.sum(arr,axis=0)

#1+4+7=12
#2+5+8=15
#7+8+9=18

array([12, 15, 18])

In [61]:
#only row wise sum
np.sum(arr,axis=1)
#1+2+3=6
#4+5+8=15
#7+8+9=24

array([ 6, 15, 24])

In [62]:
arr.mean()

np.float64(5.0)

In [63]:
arr.std()

np.float64(2.581988897471611)

In [64]:
 #index of max element
arr.argmax()

np.int64(8)

In [66]:
 #index of min element
arr.argmin()

np.int64(0)

In [76]:
#reshaping 

In [77]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [78]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])