In [1]:
import numpy as np 

In [2]:
#Array Operations 

In [3]:
#1 Arithmetic Opeartions 


In [5]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])


In [10]:
#1   2    3    4    5
#6   7    8    9    10
#--  --   --   --   --
#7   9     11   13  15
sum=a1+a2
sum

array([ 7,  9, 11, 13, 15])

In [11]:
sub=a1-a2
sub

array([-5, -5, -5, -5, -5])

In [12]:
mul=a1*a2
mul

array([ 6, 14, 24, 36, 50])

In [14]:
div=a1/a2
div

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [16]:
floor=a1//a2
floor

array([0, 0, 0, 0, 0])

In [18]:
exp = a1 ** a2
exp

array([      1,     128,    6561,  262144, 9765625])

In [19]:
#Broadcasting

In [28]:
l=[10,20,30,40]
arr=np.array(l)
arr

array([10, 20, 30, 40])

In [29]:
#if i want to add +10 in each element in an arry 
arr + 10

array([20, 30, 40, 50])

In [33]:
arr=np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [35]:
add=arr+10
add

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [38]:
mul=add*2
mul

array([[22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50],
       [52, 54, 56, 58, 60],
       [62, 64, 66, 68, 70]])

In [30]:
#Deep and Shallow copy 


In [39]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [43]:
slice=a[0:5]   #OR    slice=s[:5]
slice=slice * 10
slice

array([10, 20, 30, 40, 50])

In [44]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [46]:
a[4:8] * 2


array([10, 12, 14, 16])

In [49]:
#Deep copy

a
b=a

In [50]:
b[0]=99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [51]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [52]:
#shallow copy
#if we dont want the changes in b affect the a 
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [55]:
b=a.copy()
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [56]:
b[1]=20
b

array([99, 20,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [57]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [58]:
#Matrix operations 

In [59]:
mat1=np.array([[1,2],[3,4]])
mat2=np.array([[5,6],[7,8]])


In [60]:
mat1


array([[1, 2],
       [3, 4]])

In [61]:
mat2

array([[5, 6],
       [7, 8]])

In [64]:
#Matrix Multiplication
mul=mat1 @ mat2    #OR mat1.dot(mat2)
mul

array([[19, 22],
       [43, 50]])

In [67]:
#Transpose
a=mat1.T
a

array([[1, 3],
       [2, 4]])

In [68]:
b=mat2.T
b

array([[5, 7],
       [6, 8]])

In [69]:
#Array manupulation



In [70]:
#Stacking used to combine 2 array  (imp == we cannot perform staking on matrix)
# 3 types of stacking
# 1 -vertical stcak   2 -horizontal stack    3 -simple stack 

In [71]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])


In [73]:
#vertical stack
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [75]:
#horizontal stack
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
np.column_stack((a,b))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [77]:
#splitting array

In [78]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [82]:
#horizontal split 
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]